# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80ed1c4ba0f021273a032990b78b5352d5c800ab838a83604e59b9495ee3ca550aeb31efe32302fe57765e00cca387cbb3249768dcd93f47acbe2417afd5720c

test:
  secret_key_base: 78e88b80ebe2387d3bb7841cedd5e8f952ad5e9511ce6b73ac51488c78154a34713040274e1b379debca794e97361b4b47074fb29afe8677558c7bafcac6a3e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
